# Generated by Django 3.0.3 on 2020-07-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='datate',
            new_name='date',
        ),
    ]
